@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}
###
# PESSOAS
# Retorna todas as pessoas cadastradas
GET {{baseUrl}}/pessoas
?limit=10
&offset=0
Authorization: Bearer {{authToken}}
###

# Retorna apenas uma pessoa com base no ID
GET {{baseUrl}}/pessoas/4

###

# Criar uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "Roberto@email.com",
    "password": "123456",
    "nome": "Roberto"
}

###

# Edita uma pessoa
PATCH {{baseUrl}}/pessoas/12/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "password": "123456",
    "nome": "Chriss"
}

###

# Deleta uma pessoa
DELETE {{baseUrl}}/pessoas/2
Authorization: Bearer {{authToken}}

###

# RECADOS
# Retorna todos os recados cadastrados
GET {{baseUrl}}/recados/
?limit=10
&offset=0

###

# Retorna apenas um recado com base no ID
GET {{baseUrl}}/recados/6

###

# Criar um recado
POST {{baseUrl}}/recados/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Esse é o novo recado",
    "paraId": 12
}

###

# Edita um recado
PATCH {{baseUrl}}/recados/5/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Esse é o recado editado",
    "lido": true
}

###

# Deleta um Recado
DELETE {{baseUrl}}/recados/1
Authorization: Bearer {{authToken}}

###
# Faz o login
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "christian@email.com",
    "password": "123456"
}
###
# Re-autentica
# @name reAuthenticate
POST {{baseUrl}}/auth/refresh
Content-Type: application/json
{
    "refreshToken": "{{refreshToken}}"
}